routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', //function() {
    //return view('welcome');
    'ArticlesController@index'
)->name('home');
Route::get('home', 'HomeController@index');

/*
 * Authentication
 */
Auth::routes();

/*
 * Static pages
 */
Route::get('contact', 'PagesController@contact')->name('contact');
Route::post('contact', 'PagesController@contactMessage')->name('contact.message');
Route::get('about', 'PagesController@about')->name('about');

/*
 * App modules' pages
 */
// users
Route::resource('users', 'UsersController');

// categories
Route::resource('categories', 'CategoriesController');

// articles
Route::resource('articles/{article}/comments', 'CommentsController', ['except' => [
    'create', 'show', 'edit',
]]);
Route::get('articles/popular', 'ArticlesController@showPopular')->name('articles.showPopular');
Route::get('articles/own', 'ArticlesController@indexOwn')->name('articles.indexOwn');
Route::patch('articles/{article}/publish', 'AdminController@update')->name('articles.publish');
Route::resource('articles', 'ArticlesController');

// admin
Route::get('admin', 'AdminController@index')->name('admin.panel');
//Route::patch('admin/articles/{article}', 'AdminController@update')->name('admin.panel.publish');
//Route::patch('admin/users/{user}', 'AdminController@promote')->name('admin.panel.promote');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="/css/app.css" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ url('/login') }}">Login</a></li>
                            <li><a href="{{ url('/register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ url('/logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="/js/app.js"></script>
</body>
</html>

resources/views/layouts/email.blade.php
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- So that mobile will display zoomed in -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge"> <!-- enable media queries for windows phone 8 -->
    <meta name="format-detection" content="telephone=no"> <!-- disable auto telephone linking in iOS -->
    <title>{{ $websiteTitle }}</title>

    <style type="text/css">
        body {
            margin: 0;
            padding: 0;
            -ms-text-size-adjust: 100%;
            -webkit-text-size-adjust: 100%;
        }

        table {
            border-spacing: 0;
        }

        table td {
            border-collapse: collapse;
        }

        .ExternalClass {
            width: 100%;
        }

        .ExternalClass,
        .ExternalClass p,
        .ExternalClass span,
        .ExternalClass font,
        .ExternalClass td,
        .ExternalClass div {
            line-height: 100%;
        }

        .ReadMsgBody {
            width: 100%;
            background-color: #ebebeb;
        }

        table {
            mso-table-lspace: 0pt;
            mso-table-rspace: 0pt;
        }

        img {
            -ms-interpolation-mode: bicubic;
        }

        .yshortcuts a {
            border-bottom: none !important;
        }

        @media screen and (max-width: 599px) {
            .force-row,
            .container {
                width: 100% !important;
                max-width: 100% !important;
            }
        }
        @media screen and (max-width: 400px) {
            .container-padding {
                padding-left: 12px !important;
                padding-right: 12px !important;
            }
        }
        .ios-footer a {
            color: #aaaaaa !important;
            text-decoration: underline;
        }
    </style>
</head>

<body style="margin:0; padding:0;" bgcolor="#F0F0F0" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">

<!-- 100% background wrapper (grey background) -->
<table border="0" width="100%" height="100%" cellpadding="0" cellspacing="0" bgcolor="#F0F0F0">
    <tr>
        <td align="center" valign="top" bgcolor="#F0F0F0" style="background-color: #F0F0F0;">

            <br>

            <!-- 600px container (white background) -->
            <table border="0" width="600" cellpadding="0" cellspacing="0" class="container" style="width:600px;max-width:600px">
                <tr>
                    <td class="container-padding header" align="left" style="font-family:Helvetica, Arial, sans-serif;font-size:24px;font-weight:bold;padding-bottom:12px;color:#DF4726;padding-left:24px;padding-right:24px">
                        {{ $websiteTitle }}
                    </td>
                </tr>
                <tr>
                    <td class="container-padding content" align="left" style="padding-left:24px;padding-right:24px;padding-top:12px;padding-bottom:12px;background-color:#ffffff">
                        <br>

                        <div class="title" style="font-family:Helvetica, Arial, sans-serif;font-size:18px;font-weight:600;color:#374550">
                            {{ $request->input('subject') }}
                        </div>
                        <br>

                        <div class="body-text" style="font-family:Helvetica, Arial, sans-serif;font-size:14px;line-height:20px;text-align:left;color:#333333">
                            <p>{{ $request->input('message') }}</p>
                        </div>

                    </td>
                </tr>
                <tr>
                    <td class="container-padding footer-text" align="left" style="font-family:Helvetica, Arial, sans-serif;font-size:12px;line-height:16px;color:#aaaaaa;padding-left:24px;padding-right:24px">
                        <br><br>
                        Copyright © 2017 {{ $copyrightOwner }}
                        <br><br>

                        You are receiving this email because you opted in on our website. Update your <a href="#" style="color:#aaaaaa">email preferences</a> or <a href="#" style="color:#aaaaaa">unsubscribe</a>.
                        <br><br>

                        <strong>TAIP</strong><br>
                        <span class="ios-footer">
                            Example Street 99<br>
                            99-999 Example City<br>
                        </span>
                        <a href="http://www.acme-inc.com" style="color:#aaaaaa">{{ $websiteUrl }}</a><br>

                        <br><br>

                    </td>
                </tr>
            </table>
            <!--/600px container -->


        </td>
    </tr>
</table>
<!--/100% background wrapper-->

</body>
</html>

resources/views/layouts/footer.blade.php
<div id="footerwrap">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <h4>Bądź na bieżąco</h4>
                <div class="hline-g"></div>
                <p>
                    Zapisz się na nasz newsletter.
                </p>
                <form id="newsletter_signup">
                    <div class="input-group">
                        <input id="newsletter_email" class="form-control" type="email"
                               placeholder="Wprowadź adres e-mail">
                        <span class="input-group-btn">
		 						<button type="submit" class="btn btn-default">Zapisz</button>
                        </span>
                    </div>
                </form>
            </div>
            <div class="col-lg-3">
                <h4>Przydatne linki</h4>
                <div class="hline-g"></div>
                <ul>
                    <li><a href="{{ URL::route('contact') }}">Zgłoś błąd</a></li>
                    <li><a href="https://europa.eu/european-union/abouteuropa/cookies_pl">Informacja o cookies</a></li>
                    <li><a href="{{ URL::route('contact') }}">Reklama</a></li>
                </ul>
            </div>

            <div class="col-lg-6">
                <h4>O nas</h4>
                <div class="hline-g"></div>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nibh augue, suscipit a, scelerisque
                    sed, lacinia in, mi. Cras vel lorem. Etiam pellentesque aliquet tellus. Phasellus pharetra nulla ac
                    diam. Quisque semper justo at risus.
                </p>
            </div>
        </div><!-- /row -->
        <div class="row">
            <div id="footer-end">
                <p>
                    Copyright © 2017 TAIP {{ $copyrightOwner }}
                </p>
                <ul class="social-network">
                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#"><i class="fa fa-reddit-alien"></i></a></li>
                    <li><a href="#"><i class="fa fa-youtube"></i></a></li>
                </ul>
            </div>
        </div>
    </div><!-- /container -->
</div><!-- /footerwrap -->

resources/views/layouts/header.blade.php
 <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ URL::route('home') }}">TAIP</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-left">
                    <li class="{{ Route::currentRouteNamed('home') ? 'active' : '' }}"><a href="{{ URL::route('home') }}">GŁÓWNA</a></li>
                    <li class="{{ Route::currentRouteNamed('about') ? 'active' : '' }}"><a href="{{ URL::route('about') }}">O NAS</a></li>
                    <li class="dropdown {{ (strpos(Route::currentRouteName(), 'articles.') !== false) || (strpos(Route::currentRouteName(), 'categories.') !== false) ? 'active' : '' }}">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">ARTYKUŁY <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ URL::route('categories.index') }}">KATEGORIE</a></li>
                            {{--<li><a href="{{ URL::route('articles.showPopular') }}">NAJPOPULARNIEJSZE</a></li>--}}
                        </ul>
                    </li>
                    <li class="{{ Route::currentRouteNamed('contact') ? 'active' : '' }}"><a href="{{ URL::route('contact') }}">KONTAKT</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (Auth::guest())
                        <li class="{{ Route::currentRouteNamed('login') || Route::currentRouteNamed('register') ? 'active' : '' }}"><a href="{{ URL::route('login') }}"><i class="fa fa-sign-in"> </i> LOGOWANIE</a></li>
                    @else
                        <li class="dropdown {{ strpos(Route::currentRouteName(), 'admin.') !== false ? 'active' : '' }}">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" style="padding-top: 8px; padding-bottom: 8px;">
                                <img src="{{ URL::asset('img/avatar.png') }}" alt="{{ Auth::user()->name }}" style="height: 34px; width: 34px; margin-right: 6px" />
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{{ URL::route('articles.create') }}">
                                        <i class="fa fa-plus" aria-hidden="true"></i>
                                        DODAJ ARTYKUŁ
                                    </a>
                                </li>
                                <li>
                                    <a href="{{ URL::route('articles.indexOwn') }}">
                                        <i class="fa fa-list-ol" aria-hidden="true"></i>
                                        MOJE ARTYKUŁY
                                    </a>
                                </li>
                                @if (Auth::user()->role === 255)
                                    <li>
                                        <a href="{{ URL::route('categories.create') }}">
                                            <i class="fa fa-plus" aria-hidden="true"></i> DODAJ KATEGORIĘ
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{{ URL::route('admin.panel') }}">
                                            <i class="fa fa-cogs" aria-hidden="true"></i> PANEL ADMINISTRACYJNY
                                        </a>
                                    </li>
                                @endif
                                <li>
                                    <a href="{{ URL::route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        <i class="fa fa-sign-out" aria-hidden="true"></i>
                                        WYLOGUJ SIĘ
                                    </a>

                                    <form id="logout-form" action="{{ URL::route('logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div><!--/.nav-collapse -->


        </div>
 </div>

resources/views/layouts/sidebar.blade.php
<h4>Szukaj</h4>
<div class="hline"></div>
<p>
    <br/>
    <input type="text" class="form-control" placeholder="Wpisz kryteria">
</p>

<div class="spacing"></div>

<h4>Popularne kategorie</h4>
<div class="hline"></div>
@php
    $categories = DB::table('categories')
                  ->join('articles', 'articles.category_id', '=', 'categories.id')
                  ->select(DB::raw('categories.name as name, count(articles.id) as articles_count'))
                  ->groupBy('categories.name')
                    ->havingRaw('count(articles.id)')
                    ->limit(6)->get();
    foreach ($categories as $category) {
        echo '<p><a href="#"><i class="fa fa-angle-right"></i> ' . $category->name
        . '</a> <span class="badge badge-theme pull-right">'
        . $category->articles_count . '</span></p>';
    }

@endphp

<div class="spacing"></div>

<h4>Ostatnie komentarze</h4>
<div class="hline"></div>
<ul class="popular-posts">
    @php
        $comments = DB::table('comments')
                    ->join('users', 'comments.user_id', '=', 'users.id')
                    ->select('users.name', 'comments.created_at', 'comments.content')
                    ->orderBy('comments.created_at', 'desc')
                    ->limit(3)
                    ->get();
        foreach ($comments as $comment) {
            echo '<li><a href="#"><img src="' . URL::asset('img/avatar.png') . '" alt="' . $comment->name
            . '" class="img-responsive img-smallie"/></a>
            <p><a href="#">' . mb_strimwidth($comment->content, 0, 86, "...") . '</a></p>
            <em>' . $comment->created_at . '</em></li>';
        }
    @endphp
</ul>

<div class="spacing"></div>

<h4>Popularne tagi</h4>
<div class="hline"></div>
<p>
    <a class="btn btn-theme" href="#" role="button">Design</a>
    <a class="btn btn-theme" href="#" role="button">Wordpress</a>
    <a class="btn btn-theme" href="#" role="button">Flat</a>
    <a class="btn btn-theme" href="#" role="button">Modern</a>
    <a class="btn btn-theme" href="#" role="button">Wallpaper</a>
    <a class="btn btn-theme" href="#" role="button">HTML5</a>
    <a class="btn btn-theme" href="#" role="button">Pre-processor</a>
    <a class="btn btn-theme" href="#" role="button">Developer</a>
    <a class="btn btn-theme" href="#" role="button">Windows</a>
    <a class="btn btn-theme" href="#" role="button">Phothosop</a>
    <a class="btn btn-theme" href="#" role="button">UX</a>
    <a class="btn btn-theme" href="#" role="button">Interface</a>
    <a class="btn btn-theme" href="#" role="button">UI</a>
    <a class="btn btn-theme" href="#" role="button">Blog</a>
</p>