routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', //function() {
    //return view('welcome');
    'ArticlesController@index'
)->name('home');
Route::get('home', 'HomeController@index');

/*
 * Authentication
 */
Auth::routes();

/*
 * Static pages
 */
Route::get('contact', 'PagesController@contact')->name('contact');
Route::post('contact', 'PagesController@contactMessage')->name('contact.message');
Route::get('about', 'PagesController@about')->name('about');

/*
 * App modules' pages
 */
// users
Route::resource('users', 'UsersController');

// categories
Route::resource('categories', 'CategoriesController');

// articles
Route::resource('articles/{article}/comments', 'CommentsController', ['except' => [
    'create', 'show', 'edit',
]]);
Route::get('articles/popular', 'ArticlesController@showPopular')->name('articles.showPopular');
Route::get('articles/own', 'ArticlesController@indexOwn')->name('articles.indexOwn');
Route::patch('articles/{article}/publish', 'AdminController@update')->name('articles.publish');
Route::resource('articles', 'ArticlesController');

// admin
Route::get('admin', 'AdminController@index')->name('admin.panel');
//Route::patch('admin/articles/{article}', 'AdminController@update')->name('admin.panel.publish');
//Route::patch('admin/users/{user}', 'AdminController@promote')->name('admin.panel.promote');

app/Article.php
<?php

namespace Taip;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'category_id', 'intro_content', 'full_content', 'img',
    ];

    /**
     * Get article's author.
     */
    public function user() {
        return $this->belongsTo(User::class);
    }

    /**
     * Get article's category.
     */
    public function category() {
        return $this->belongsTo(Category::class);
    }

    /**
     * Get all of the article's comments.
     */
    public function comments()
    {
        return $this->morphMany(Comment::class, 'commentable');
    }
}

app/Http/Controllers/ArticlesController.php
<?php

namespace Taip\Http\Controllers;

use Illuminate\Http\Request;
use Debugbar;
use Exception;
use Session;
use Taip\Article;
use Taip\Category;
use Taip\Comment;
use Taip\Http\Requests\CreateArticleRequest;
use Illuminate\Support\Facades\Auth;

class ArticlesController extends Controller {
    public function __construct() {
        $this->middleware('auth')->only(['create', 'store', 'edit', 'update', 'destroy']);
    }

    /**
     * Show article list (by date, descending).
     */
    public function index() {
        // https://laravel.com/docs/5.4/eloquent-relationships#eager-loading
        $articles = Article::with('user', 'category')->latest()->where('published', '=', true)->get();
        return view('articles.index', compact('articles'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function indexOwn() {
        $articles = Article::with('user', 'category')->latest()->where('user_id', '=', Auth::user()->id)->get();
        return view('articles.index', compact('articles'));
    }

    /*public function indexCategory(Category $category) {
        $articles = Article::latest()->where('category_id', '=', $category->id)->get();
        return view('articles.index', ['articles' => $articles]);
    }*/

    /**
     * Show the specified article.
     *
     * @param Article $article
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Article $article) {
        $commentsCount = $article->comments()->count();
        return view('articles.show', compact('article', 'commentsCount'));
    }

    /**
     * Show the form for adding an article.
     */
    public function create() {
        // ::lists is deprecated, use ::pluck instead
        $categories = Category::pluck('name', 'id');
        return view('articles.create')->with('categories', $categories);
    }

    /**
     * Store newly created article in storage.
     * TODO: proper form validation
     *
     * @param CreateArticleRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CreateArticleRequest $request) {
        // TODO: store img under public in storage
        $img = $request->file('img')->store('imgs');
        $article = new Article($request->all());
        $article->img = $img;
        try {
            Auth::user()->articles()->save($article);
        }
        catch (Exception $e) {
            Debugbar::addThrowable($e);
            return redirect()->back();
        }

        Session::flash('article_created_deleted', 'Artykuł został dodany.');
        return redirect()->route('articles.index');
    }

    /**
     * Show the form for editing an article.
     *
     * @param Article $article
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Article $article) {
        $categories = Category::pluck('name', 'id');
        return view('articles.edit', compact('categories', 'article'));
    }


    /**
     * Update the article in storage.
     *
     * @param CreateArticleRequest $request
     * @param Article $article
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(CreateArticleRequest $request, Article $article) {
        $article->update($request->all());
        Session::flash('article_edited', 'Artykuł zmieniony pomyślnie.');
        return redirect('articles/' . $article->id);
    }


    /**
     * Remove the article from storage.
     *
     * @param Article $article
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Article $article) {
        $article->delete();
        Session::flash('article_created_deleted', 'Artykuł usunięty pomyślnie.');
        return redirect()->route('articles.index');
    }
}

resources/views/articles/create.blade.php
@extends('master')
@section('title')
    Dodawanie artykułu
@endsection
@section('content')
    <div class="container mtb">
    <div class="row">
        <div class="col-md-8 col-md-offset-1">
            <div class="card">
                <div class="panel-body">
                    <!-- Formularz -->
                    {!! Form::open(['route' => 'articles.index', 'files' => true, 'class' => 'form-horizontal']) !!}

                        @include('articles.form', ['sendText' => 'Dodaj artykuł'])

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
    </div>
@endsection

resources/views/articles/edit.blade.php
@extends('master')
@section('title')
    Edycja artykułu
@endsection
@section('content')
    <div class="container mtb">
        <div class="row">
            <div class="col-md-8 col-md-offset-1">
                <div class="card">
                    <div class="panel-body">
                        <!-- Formularz -->
                        {!! Form::model($article, ['route' => ['articles.update', $article->id], 'method' => 'PATCH', 'class' => 'form-horizontal']) !!}

                            @include('articles.form', ['sendText' => 'Zapisz zmiany'])

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/articles/form.blade.php
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul style="float: none; list-style: none; margin: 0; padding: 0;">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<div class="form-group">
    <div class="col-md-3 control-label">
        {!! Form::label('title', 'Tytuł') !!}
    </div>
    <div class="col-md-9">
        {!! Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'Wprowadź tytuł', 'required']) !!}
    </div>
</div>

<div class="form-group">
    <div class="col-md-3 control-label">
        {!! Form::label('intro_content', 'Wstęp') !!}
    </div>
    <div class="col-md-9">
        {!! Form::textarea('intro_content', null, ['class' => 'form-control', 'placeholder' => 'Wprowadź wstęp artykułu (wyświetlany na stronie głównej)', 'rows' => '4', 'required']) !!}
    </div>
</div>

<div class="form-group">
    <div class="col-md-3 control-label">
        {!! Form::label('full_content', 'Treść') !!}
    </div>
    <div class="col-md-9">
        {!! Form::textarea('full_content', null, ['class' => 'form-control', 'placeholder' => 'Wprowadź pozostałą treść artykułu (wyświetlany na stronie danego artykułu)', 'required']) !!}
    </div>
</div>

<div class="form-group">
    <div class="col-md-3 control-label">
        {!! Form::label('category_id', 'Kategoria') !!}
    </div>
    <div class="col-md-9">
        {!! Form::select('category_id', $categories, null, ['class' => 'form-control', 'placeholder' => 'Wybierz kategorię', 'required']) !!}
    </div>
</div>

@if ($sendText == 'Dodaj artykuł')
<div class="form-group">
    <div class="col-md-3 control-label">
        {!! Form::label('img', 'Obrazek') !!}
    </div>
    <div class="col-md-9">
        {!! Form::file('img', ['required']) !!}
    </div>
</div>
@endif

<div class="form-group">
    <div class="col-md-9 col-md-offset-3">
        {!! Form::button('<i class="fa fa-floppy-o" aria-hidden="true"></i> ' . $sendText, ['type' => 'submit', 'class' => 'btn btn-theme']) !!}
    </div>
</div>

resources/views/articles/index.blade.php
@extends('master')
@section('title')
    Najnowsze artykuły
@endsection
@section('content')
    <div class="container mtb">
        @if (Session::has('article_created_deleted'))
            <div class="alert alert-success alert-dismissable fade in">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ Session::get('article_created_deleted') }}
            </div>
        @endif
        <div class="row">

            <!-- BLOG POSTS LIST -->
            <div class="col-lg-8">

                @foreach ($articles as $article)
                <!-- Article brief -->
                <p><img class="img-responsive" src="{{ URL::asset(Storage::url($article->img)) }}"></p>
                <a href="{{ URL::route('articles.show', ['id' => $article->id]) }}"><h3 class="ctitle">{{ $article->title }}</h3></a>
                <div class="bottom-article">
                    <ul class="meta-post">
                        <li><i class="fa fa-clock-o"></i> <span>{{ date('F d, Y G:i', strtotime($article->created_at)) }}</span></li>
                        <li><i class="fa fa-user"></i><a href="#"> {{ $article->user->name }}</a></li>
                        {{--<li><i class="fa fa-comments"></i><a href="{{ URL::route('articles.show', ['id' => $article->id]) }}#comments_section">3 komentarze</a></li>--}}
                        <li><i class="fa fa-tags"></i><a href="#">{{ $article->category->name }}</a></li>
                    </ul>
                </div>
                <p>{{ $article->intro_content }}</p>
                <p><a href="{{ URL::route('articles.show', ['id' => $article->id]) }}">Czytaj dalej</a></p>
                <div class="hline"></div>

                <div class="spacing"></div>

                @endforeach
            </div><!--/col-lg-8 -->


            <!-- SIDEBAR -->
            <div class="col-lg-4">
                @include ('layouts.sidebar')
            </div>
        </div><!--/row -->
    </div><!--/container -->
@endsection

resources/views/articles/show.blade.php
@extends('master')
@section('title')
    {{ $article->title }}
@endsection
@section('article_path')
    <ol class="breadcrumb">
        <li><a href="{{ URL::route('home') }}"><i class="fa fa-home"></i></a></li>
        <li>
            <a href="{{--{{ URL::route('categories.show', $article->category_id) }}--}}">{{ $article->category->name }}</a>
        </li>
        <li class="active">{{ $article->title }}</li>
    </ol>
@endsection
@section('content')
    <div class="container mtb">
        @if (Session::has('article_edited'))
            <div class="alert alert-success alert-dismissable fade in">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ Session::get('article_edited') }}
            </div>
        @endif
        <div class="row">

            <!-- SINGLE POST -->
            <div class="col-lg-8">
                <!-- Blog Post 1 -->
                <p><img class="img-responsive" src="{{ URL::asset(Storage::url($article->img)) }}"></p>
                <h3 class="ctitle"></h3>
                <p>{{ $article->intro_content }}</p>
                <p>{{ $article->full_content }}</p>

                <div class="bottom-article">
                    <ul class="meta-post">
                        <li><i class="fa fa-clock-o"></i>
                            <span>{{ date('F d, Y G:i', strtotime($article->created_at)) }}</span></li>
                        <li><i class="fa fa-user"></i><a href="#">{{ $article->user->name }}</a></li>
                        <li><i class="fa fa-comments"></i><a href="#comments">{{ $commentsCount }} komentarzy</a></li>
                        <li>
                            <i class="fa fa-tags"></i>
                            <a href="{{--{{ URL::route('categories.show', $article->category_id) }}--}}">{{ $article->category->name }}</a>
                        </li>
                    </ul>
                </div>

                @can ('update', $article)
                    <div style="margin: 10px 0;">
                        <a href="{{ URL::route('articles.edit', $article->id) }}" class="btn btn-theme">
                            <i class="fa fa-pencil" aria-hidden="true"></i> Edytuj
                        </a>
                        @can ('delete', $article)
                            <a href="{{ URL::route('articles.index') }}" class="btn btn-theme"
                               onclick="event.preventDefault();
                                    document.getElementById('article_delete_form').submit();">
                                <i class="fa fa-trash-o" aria-hidden="true"></i> Usuń
                            </a>

                            {!! Form::open(['route' => ['articles.destroy', $article->id], 'method' => 'DELETE', 'style' => 'display: none;', 'id' => 'article_delete_form']) !!}
                            {!! Form::close() !!}
                        @endcan
                    </div>
                @endcan

                <div class="comment-area" id="comments">
                    {{-- jquery-comments.js plugin is injected here --}}
                </div>

            </div><!--/col-lg-8 -->

            <!-- SIDEBAR -->
            <div class="col-lg-4">
                @include ('layouts.sidebar')
            </div>
        </div><!--/row -->
    </div><!--/container -->
@endsection
@section ('customJs')
    @php
        $resourceId = $article->id;
    @endphp
    <script>
        @if (isset($resourceId) && $resourceId != null)
            var TaipMeta = {
                commentsRouteUrl: "{{ URL::route('comments.index', $resourceId) }}",
            };
        @endif
        @if (Auth::guest())
            TaipMeta.currentUserName = null;
        @else
            TaipMeta.currentUserName = "{{ Auth::user()->name }}";
            TaipMeta.currentUserId = "{{ Auth::id() }}";
        @endif
    </script>
    <script src="{{ URL::asset('js/jquery-comments.js') }}"></script>
    <script src="{{ URL::asset('js/app.js') }}"></script>
@endsection